---

- name: make directory
  file:
    path: "/home/jenkins/.ssh"
    state: directory
    mode: 0755
    recurse: yes

- name: create empty file
  file:
    path: "/home/jenkins/.ssh/authorized_keys"
    state: touch

- name: copy public key
  lineinfile:
    path: "/home/jenkins/.ssh/authorized_keys"
    line: "{{ pubkey }}"
